spring:
  data:
    mongodb:
      authentication-database: admin
      username: dispatcher
      password: dispatcher
      database: daily-reports
      port: 27017
      host: localhost
      auto-index-creation: true
#spring:
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL10Dialect
#        format_sql: true
#    hibernate:
#      ddl-auto: none
#  sql:
#    init:
#      mode: always
#  datasource:
#    driverClassName: org.postgresql.Driver
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#
#---
#
#spring:
#  config:
#    activate:
#      on-profile: dev
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL10Dialect
#        format_sql: true
#        show_sql: true
#    hibernate:
#      ddl-auto: none
#  sql:
#    init:
#      mode: always
#  datasource:
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/dailyreports
#    username: root
#    password: root